import { Question } from "@/types";

export const questionsData: Record<string, Question[]> = {
  "password-management": [
    {
      id: "pm1",
      categoryId: "1",
      question: "What is the recommended minimum length for a strong password?",
      options: ["6 characters", "8 characters", "12 characters", "16 characters"],
      correctAnswer: 2,
    },
    {
      id: "pm2",
      categoryId: "1",
      question: "Which of the following is the most secure password practice?",
      options: [
        "Using the same password for all accounts",
        "Writing passwords on sticky notes",
        "Using a password manager",
        "Sharing passwords with trusted friends",
      ],
      correctAnswer: 2,
    },
    {
      id: "pm3",
      categoryId: "1",
      question: "What should you do if you suspect your password has been compromised?",
      options: [
        "Wait a few days to see if anything happens",
        "Change it immediately",
        "Delete your account",
        "Ignore it",
      ],
      correctAnswer: 1,
    },
    {
      id: "pm4",
      categoryId: "1",
      question: "What is two-factor authentication (2FA)?",
      options: [
        "Using two different passwords",
        "An extra layer of security requiring a second verification method",
        "A type of password manager",
        "A way to recover forgotten passwords",
      ],
      correctAnswer: 1,
    },
    {
      id: "pm5",
      categoryId: "1",
      question: "Which password is the strongest?",
      options: ["password123", "P@ssw0rd", "Tr0ub4dor&3", "correcthorsebatterystaple"],
      correctAnswer: 3,
    },
  ],
  "social-media-privacy": [
    {
      id: "sm1",
      categoryId: "2",
      question: "What information should you avoid sharing on social media?",
      options: [
        "Your vacation photos after returning",
        "Your exact location in real-time",
        "Your favorite movies",
        "Your pet's name",
      ],
      correctAnswer: 1,
    },
    {
      id: "sm2",
      categoryId: "2",
      question: "What is the best privacy setting for your social media profile?",
      options: ["Public", "Friends only", "Custom", "It doesn't matter"],
      correctAnswer: 1,
    },
    {
      id: "sm3",
      categoryId: "2",
      question: "Should you accept friend requests from people you don't know?",
      options: ["Yes, to make more friends", "No, it could be a security risk", "Only if they have mutual friends", "Yes, if their profile looks legitimate"],
      correctAnswer: 1,
    },
    {
      id: "sm4",
      categoryId: "2",
      question: "What should you do before posting a photo with friends?",
      options: [
        "Post immediately",
        "Get their permission first",
        "Tag them without asking",
        "Make the post public",
      ],
      correctAnswer: 1,
    },
    {
      id: "sm5",
      categoryId: "2",
      question: "How often should you review your privacy settings?",
      options: ["Never", "Once a year", "Regularly (every few months)", "Only when creating an account"],
      correctAnswer: 2,
    },
  ],
  "safe-browsing": [
    {
      id: "sb1",
      categoryId: "3",
      question: "What does 'HTTPS' in a website URL indicate?",
      options: [
        "The site is popular",
        "The connection is encrypted and secure",
        "The site loads faster",
        "It's a government website",
      ],
      correctAnswer: 1,
    },
    {
      id: "sb2",
      categoryId: "3",
      question: "What should you do if your browser warns about an unsafe website?",
      options: [
        "Proceed anyway",
        "Leave the site immediately",
        "Disable security warnings",
        "Clear your cookies",
      ],
      correctAnswer: 1,
    },
    {
      id: "sb3",
      categoryId: "3",
      question: "What is a browser cookie?",
      options: [
        "A virus",
        "A small piece of data stored by websites",
        "A type of advertisement",
        "A browser extension",
      ],
      correctAnswer: 1,
    },
    {
      id: "sb4",
      categoryId: "3",
      question: "Why should you keep your browser updated?",
      options: [
        "For new features only",
        "To fix security vulnerabilities",
        "It's not necessary",
        "Only if the browser crashes",
      ],
      correctAnswer: 1,
    },
    {
      id: "sb5",
      categoryId: "3",
      question: "What is private/incognito browsing?",
      options: [
        "Complete anonymity online",
        "Prevents the browser from storing your history locally",
        "Makes you invisible to hackers",
        "Speeds up your internet",
      ],
      correctAnswer: 1,
    },
  ],
  "phishing-awareness": [
    {
      id: "pa1",
      categoryId: "4",
      question: "What is phishing?",
      options: [
        "A type of sport",
        "An attempt to steal sensitive information through deception",
        "A legitimate email marketing technique",
        "A password recovery method",
      ],
      correctAnswer: 1,
    },
    {
      id: "pa2",
      categoryId: "4",
      question: "What is a common sign of a phishing email?",
      options: [
        "Professional design",
        "Urgent language and threats",
        "Personalized greeting",
        "Company logo",
      ],
      correctAnswer: 1,
    },
    {
      id: "pa3",
      categoryId: "4",
      question: "What should you do if you receive a suspicious email asking for personal information?",
      options: [
        "Reply with the information",
        "Click the link to verify",
        "Delete it and report as spam",
        "Forward it to friends",
      ],
      correctAnswer: 2,
    },
    {
      id: "pa4",
      categoryId: "4",
      question: "How can you verify if an email is legitimate?",
      options: [
        "Check the sender's email address carefully",
        "Trust the company logo",
        "Click the link to see where it goes",
        "Reply and ask if it's real",
      ],
      correctAnswer: 0,
    },
    {
      id: "pa5",
      categoryId: "4",
      question: "What is spear phishing?",
      options: [
        "Fishing with a spear",
        "A targeted phishing attack on specific individuals",
        "Mass email spam",
        "A type of computer virus",
      ],
      correctAnswer: 1,
    },
  ],
  "mobile-app-permissions": [
    {
      id: "map1",
      categoryId: "5",
      question: "Why should you review app permissions?",
      options: [
        "It's not necessary",
        "To ensure apps only access what they need",
        "To make apps run faster",
        "To save battery life",
      ],
      correctAnswer: 1,
    },
    {
      id: "map2",
      categoryId: "5",
      question: "Is it normal for a flashlight app to request access to your contacts?",
      options: [
        "Yes, all apps need this",
        "No, this is suspicious",
        "Only on Android",
        "Only on iOS",
      ],
      correctAnswer: 1,
    },
    {
      id: "map3",
      categoryId: "5",
      question: "What should you do before installing a new app?",
      options: [
        "Install it immediately",
        "Check reviews and requested permissions",
        "Only check the number of downloads",
        "Trust the app store completely",
      ],
      correctAnswer: 1,
    },
    {
      id: "map4",
      categoryId: "5",
      question: "Can you change app permissions after installation?",
      options: [
        "No, they're permanent",
        "Yes, in your device settings",
        "Only by uninstalling",
        "Only on newer devices",
      ],
      correctAnswer: 1,
    },
    {
      id: "map5",
      categoryId: "5",
      question: "What does location permission allow an app to do?",
      options: [
        "Access your GPS coordinates",
        "Control your phone",
        "Read your messages",
        "Make phone calls",
      ],
      correctAnswer: 0,
    },
  ],
};
